name: Data Processing Workflow

on:
 push:
    branches:
      - main
 workflow_dispatch:

jobs:
  fetch-process-upload:
    runs-on: ubuntu-22.04
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          echo "Upgrading pip..."
          python -m pip install --upgrade pip
          echo "Installing dependencies..."
          pip install requests psycopg2-binary

      - name: Set environment variable
        run: echo "ENVIRONMENT=development" >> $GITHUB_ENV

      - name: Log Environment Variables
        run: |
          # echo "DATA_URL: https://medlineplus.gov/xml/mplus_topics_compressed_2024-10-31.zip"
          # echo "DB_HOST: postgres-medlineplus-t3xk6cb502vjr.cpln.app"
          # echo "DB_PORT: 5432"
          # echo "DB_NAME: medlineplus"
          # echo "DB_USER: postgres"
          echo  "DATA_URL: ${{ secrets.DATA_URL }}"
          echo  "DB_HOST: ${{ secrets.DB_HOST }}"
          echo  "DB_PORT: ${{ secrets.DB_PORT }}"
          echo  "DB_NAME: ${{ secrets.DB_NAME }}"
          echo  "DB_USER: ${{ secrets.DB_USER }}"
          echo  "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"

      - name: Run data fetch and process script
        env:
          DATA_URL: https://medlineplus.gov/xml/mplus_topics_compressed_2024-10-31.zip
          DB_HOST: postgres-medlineplus-t3xk6cb502vjr.cpln.app
          DB_PORT: 5432
          DB_NAME: medlineplus
          DB_USER: postgres
          DB_PASSWORD: postgres
        run: |
          echo "Starting data fetch and processing..."
          python fetch_and_process_medlineplus_data.py
          echo "Data fetch and processing completed."
