name: Data Processing Workflow

on:
 push:
    branches:
      - main
 workflow_dispatch:
 schedule:
    - cron: '*/10 * * * *'

jobs:
  fetch-process-upload:
    runs-on: ubuntu-22.04
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          echo "Upgrading pip..."
          python -m pip install --upgrade pip
          echo "Installing dependencies..."
          pip install requests psycopg2-binary

      - name: Set environment variable
        run: echo "ENVIRONMENT=development" >> $GITHUB_ENV

      - name: Log Environment Variables
        run: |
          echo  "DATA_URL: ${{ secrets.DATA_URL }}"
          echo  "DB_HOST: ${{ secrets.DB_HOST }}"
          echo  "DB_PORT: ${{ secrets.DB_PORT }}"
          echo  "DB_NAME: ${{ secrets.DB_NAME }}"
          echo  "DB_USER: ${{ secrets.DB_USER }}"
          echo  "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"
      
      - name: Print environment variables (for debugging)
        run: printenv

      - name: Run data fetch and process script
        env:
          DATA_URL: ${{ secrets.DATA_URL }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Starting data fetch and processing..."
          python fetch_and_process_medlineplus_data.py
          echo "Data fetch and processing completed."
