name: Submit Questionnaire

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  run-questionnaire:
    runs-on: ubuntu-22.04
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script to submit questionnaire
        run: |
          echo "Starting data Posting into public hapi"
          python post_data_into_public_hapi.py
          echo "Data posting completed"
